axios = require('axios')
getRightUrl = require('./auth')

profileRoute = (req, res) ->
  if !req.session.id and !req.session.node_url
    res.redirect '/login'
  res.view 'profile', title: 'Profile'
  return

module.exports = profileRoute: profileRoute

# ---
# generated by js2coffee 2.2.0
